image:
  file: .gitpod.dockerfile
tasks:
  - before: cp -p chrome_sandbox /usr/local/sbin/chrome-devel-sandbox && export CHROME_DEVEL_SANDBOX=/usr/local/sbin/chrome-devel-sandbox
    init: npm i && npm rebuild --build-from-source && npm run build
    command: npm run serve:dev
ports:
  - port: 8081
    onOpen: open-preview

github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false
    addLabel: false
